export const colors = {
  // Design system palette
  surface: '#fdf9f3',
  background: '#fdf9f3',
  primary: '#322214',
  primaryContainer: '#4a3728',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#bba08c',
  secondary: '#9a4600',
  secondaryContainer: '#fd8a3e',
  onSecondary: '#ffffff',
  onSurface: '#1c1c18',
  onSurfaceVariant: '#4e453e',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f7f3ed',
  surfaceContainer: '#f1ede7',
  surfaceContainerHigh: '#ebe8e2',
  outline: '#80756d',
  outlineVariant: '#d2c4bb',

  // Legacy aliases kept for LilyChat compatibility
  peach: '#fd8a3e',
  peachDeep: '#9a4600',
  peachLight: '#ffdbc9',
  peachBg: '#fdf9f3',
  green: '#A8D5B5',
  greenDeep: '#7DBF96',
  greenLight: '#D6EFE0',
  white: '#FFFFFF',
  text: '#322214',
  textLight: '#4e453e',
  border: '#d2c4bb',
};
